JuliaReach/ReachabilityBenchmarks

models/SLICOT/beam/beam.jl
models/SLICOT/building/building.jl
models/SLICOT/cdplayer/cdplayer.jl
models/SLICOT/fom/fom.jl
models/SLICOT/heat/heat.jl
models/SLICOT/iss/iss.jl
models/SLICOT/mna1/mna1.jl
models/SLICOT/mna5/mna5.jl
models/SLICOT/motor/motor.jl
models/SLICOT/pde/pde.jl

@mforets:
* Do we want to merge this? If yes, what should be the default partition/set type?
* Do we want to have common options for reach and check?

use 1D blocks and Interval set type

---

models/SLICOT/mna5/mna5.jl

fix MNA5 with HPolygon type (odd dimension)

---

models/SLICOT/fom/fom.jl

#19 - Use lazy_expm for FOM

---

README.md
models/SLICOT/beam/beam.jl
models/SLICOT/building/building.jl
models/SLICOT/cdplayer/cdplayer.jl
models/SLICOT/fom/fom.jl
models/SLICOT/heat/heat.jl
models/SLICOT/iss/iss.jl
models/SLICOT/mna1/mna1.jl
models/SLICOT/mna5/mna5.jl
models/SLICOT/motor/motor.jl
models/SLICOT/pde/pde.jl
src/benchmark_all.jl
src/check_1D_dense.jl
src/check_1D_discrete.jl
src/model_library.jl
src/plot_reach.jl
src/reach_1D_all.jl
src/reach_1D_single.jl
src/reach_2D_box_two.jl
src/reach_2D_eps_two.jl

#21 - SLICOT benchmark script

---

models/SLICOT/fom/fom.jl
models/SLICOT/iss/iss.jl
src/benchmark_all.jl
src/check_1D_dense.jl
src/check_kD_dense.jl
src/check_kD_discrete.jl
src/collect_results.sh
src/reach_1D_all.jl

* Not realistic: Find the right setting for FOM in dense mode.

[WIP] Use lazy inputs and bigger partition for ISS & FOM

---

README.md

Fix an error in the README (thanks @kostakoida  !!)

splat iss in README

---

models/SpaceEx/FilteredOscillator/FilteredOscillator.jl

Fixed projection for lazy discrete operator

---

src/plot_reach.jl

See https://github.com/JuliaReach/Reachability.jl/pull/415. See also https://github.com/JuliaReach/Reachability.jl/issues/413.

update plot reach

---

models/HSCC2019/create_figure_2.jl
models/HSCC2019/create_figure_3.jl
models/HSCC2019/create_figure_5.jl

#39 - increase font for axis labels

---

models/HSCC2019/create_figure_1.jl
models/HSCC2019/create_figure_2.jl
models/HSCC2019/create_figure_3.jl
models/HSCC2019/create_figure_5.jl

See #39.
* Add script to recreate Figure 1.
* Plot to PDF files.

#39 - Pictures

---

models/SpaceEx/FilteredOscillator/FilteredOscillator.jl

Use ConstrainedLinearMap in resets of filtered oscillator

---

models/Custom/toy/toy.jl
models/SLICOT/beam/beam.jl
models/SLICOT/building/building.jl
models/SLICOT/cdplayer/cdplayer.jl
models/SLICOT/fom/fom.jl
models/SLICOT/heat/heat.jl
models/SLICOT/iss/iss.jl
models/SLICOT/mna1/mna1.jl
models/SLICOT/mna5/mna5.jl
models/SLICOT/motor/motor.jl
models/SLICOT/pde/pde.jl
models/SpaceEx/crane/crane.jl
models/SpaceEx/helicopter/helicopter.jl

* update properties to SLICOT and SpaceEx models
* add `SparseArrays` requirements to SLICOT models

Update properties and add SparseArrays

---

models/ARCH/AFF/Platooning/Platooning.jl

This requires <strike> https://github.com/JuliaReach/Reachability.jl/pull/489 and</strike> https://github.com/JuliaReach/LazySets.jl/issues/1144 to work.

Faster setting for Platooning model

---

models/ARCH/NLN/LaubLoomis/laubloomis_TMJets.jl
models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl
models/ARCH/NLN/VanDerPol/vanderpol_TMJets.jl
models/ARCH/NLN/VanDerPol/vanderpol_benchmark.jl

Update Van der Pol and LaubLoomis to use (t, x) for check property

---

models/ARCH/NLN/LaubLoomis/laubloomis_TMJets.jl
models/ARCH/NLN/LaubLoomis/laubloomis_benchmark.jl
models/ARCH/NLN/VanDerPol/vanderpol_TMJets.jl

Update AFF benchs (van der pol, laub loomis)

---

models/ARCH/AFF/ARCH-COMP_2019.jl
models/ARCH/AFF/Platooning/Platooning.jl
models/ARCH/AFF/Platooning/Platooning_benchmark.jl
models/ARCH/AFF/Rendezvous/SpacecraftRendezvous.jl
models/ARCH/AFF/Rendezvous/SpacecraftRendezvous_benchmark.jl

#93 - Benchmark scripts for AFF

---

models/ARCH/NLN/LaubLoomis/laubloomis_TMJets.jl
models/ARCH/NLN/Quadrotor/quad.jl
models/ARCH/NLN/Quadrotor/quad_TMJets.jl
models/ARCH/NLN/Quadrotor/quad_benchmark.jl

Add quad TMJets

---

models/ARCH/AFF/SpaceStation/iss_BFFPSV18.jl
models/ARCH/AFF/SpaceStation/iss_benchmark.jl

Currently the plotting crashes because of a dimension mismatch (probably related to the fact that here we use a projection matrix).

Plots for ISS model

---

models/ARCH/AFF/Building/building.jl
models/ARCH/AFF/Gearbox/Gearbox.jl
models/ARCH/AFF/Platooning/Platooning.jl
models/ARCH/AFF/SpaceStation/iss.jl
models/SLICOT/beam/beam.jl
models/SLICOT/building/building.jl
models/SLICOT/cdplayer/cdplayer.jl
models/SLICOT/fom/fom.jl
models/SLICOT/heat/heat.jl
models/SLICOT/iss/iss.jl
models/SLICOT/mna1/mna1.jl
models/SLICOT/mna5/mna5.jl
models/SLICOT/motor/motor.jl
models/SLICOT/pde/pde.jl
models/SpaceEx/FilteredOscillator/FilteredOscillator.jl

#99 - Use B matrix

---

models/ARCH/AFF/Platooning/Platooning_benchmark.jl

Requires https://github.com/JuliaReach/Reachability.jl/pull/549.

Use proper unbounded setting in Platooning model

---

models/ARCH/AFF/Rendezvous/SpacecraftRendezvous.jl

Fix inputs for Spacecraft Rendezvous benchmark

---

models/ARCH/AFF/Gearbox/Gearbox.jl

These are minor changes that unfortunately do not help.
* Use the SpaceEx invariant in the first location.
* Let timer run in the second location (should not have an impact).
* Update some comments.

Minor changes in gearbox model

---

models/ARCH/AFF/Rendezvous/SpacecraftRendezvous.jl
models/ARCH/AFF/Rendezvous/SpacecraftRendezvous_benchmark.jl

These are just the new scenarios.
The (old) settings still need to be evaluated and adapted.

New scenarios for Spacecraft Rendezvous model

---

models/ARCH/AFF/Gearbox/Gearbox.jl
models/Custom/projectile/projectile.jl
models/SLICOT/mna1/mna1.jl
models/SLICOT/mna5/mna5.jl
models/SpaceEx/FilteredOscillator/FilteredOscillator.jl

Closes #102.
I decided to keep the Platooning model as is for efficiency.
The Spacecraft-Rendezvous model will be updated in #105.

#102 - Use CACCS for affine systems with constant vectors

---

models/ARCH/AFF/Powertrain/Powertrain.jl

In [Fig. 7 , https://easychair.org/publications/paper/4cGr] the plots are shown in the x1-x3 plane.

Plot vars in the x1-x3 plane

---

models/ARCH/AFF/Rendezvous/SpacecraftRendezvous.jl

* reorder constraints
* rename modes
* fix typo in comment

Minor revision Spacecraft Rendezvous model

---

models/ARCH/NLN/SpacecraftRendezvous/spacecraft_rendezvous.jl

#59 - Spacecraft Rendezvous model with TMJets

---

models/ARCH/AFF/SpaceStation/iss_benchmark.jl

Better ISS plots

---

models/ARCH/NLN/VanDerPol/vanderpol.jl
models/ARCH/NLN/VanDerPol/vanderpol_benchmark.jl

For later: how to pass mu to the taylorized function as a parameter?
---
CC: @lbenet

Update Van der Pol benchmark

---

models/ARCH/NLN/VanDerPol/vanderpol_benchmark.jl

[vanderpol_case_all.pdf](https://github.com/JuliaReach/ReachabilityBenchmarks/files/3025421/vanderpol_case_all.pdf)

Tweaks in vdp plot

---

models/LinearSwitcher/config.cfg
models/LinearSwitcher/ls.jl
models/LinearSwitcher/ls_helper.jl
models/LinearSwitcher/model.xml

https://ths.rwth-aachen.de/research/projects/hypro/5-dimensional-switching-linear-system/

Add Linear Switching System

---

models/ARCH/AFF/SpaceStation/iss_benchmark.jl

This reverts a recent change in #182.

Revert unapproved changes to ISS model

---

models/ARCH/AFF/Building/building.jl
models/ARCH/AFF/Gearbox/Gearbox.jl
models/ARCH/AFF/Platooning/Platooning.jl
models/ARCH/AFF/Powertrain/Powertrain.jl
models/ARCH/AFF/Rendezvous/SpacecraftRendezvous.jl
models/ARCH/AFF/SpaceStation/iss.jl

- add `ReachabilityBenchmarks` for `@relpath` macro
- remove redundant packages

Fix packages in ARCH benchmarks

---

models/ARCH/AFF/Building/building.jl
models/ARCH/AFF/Gearbox/Gearbox.jl
models/ARCH/AFF/Platooning/Platooning.jl
models/ARCH/AFF/Powertrain/Powertrain.jl
models/ARCH/AFF/Rendezvous/SpacecraftRendezvous.jl
models/ARCH/AFF/SpaceStation/iss.jl
models/ARCH/NLN/LaubLoomis/laubloomis_MP.jl
models/ARCH/NLN/Quadrotor/quadrotor_MP.jl
models/ARCH/NLN/SpacecraftRendezvous/spacecraft.jl
models/ARCH/NLN/VanDerPol/vanderpol_MP.jl
models/Crane/crane.jl
models/FilteredOscillator/FilteredOscillator.jl
models/Helicopter/helicopter.jl
models/SLICOT/beam/beam_specifications.jl
models/SLICOT/building/building_specifications.jl
models/SLICOT/cdplayer/cdplayer_specifications.jl
models/SLICOT/fom/fom_specifications.jl
models/SLICOT/heat/heat_specifications.jl
models/SLICOT/iss/iss_specifications.jl
models/SLICOT/mna1/mna1_specifications.jl
models/SLICOT/mna5/mna5_specifications.jl
models/SLICOT/motor/motor_specifications.jl
models/SLICOT/pde/pde_specifications.jl
models/Switching/ls.jl
models/Toy/toy.jl

:warning: only to be merged after the next release of `Reachability`

Use MathematicalPredicates

---

models/SLICOT/beam/beam_run.jl
models/SLICOT/beam/beam_specifications.jl
models/SLICOT/building/building_run.jl
models/SLICOT/building/building_specifications.jl
models/SLICOT/cdplayer/cdplayer_run.jl
models/SLICOT/cdplayer/cdplayer_specifications.jl
models/SLICOT/fom/fom_run.jl
models/SLICOT/fom/fom_specifications.jl
models/SLICOT/heat/heat_run.jl
models/SLICOT/heat/heat_specifications.jl
models/SLICOT/iss/iss_run.jl
models/SLICOT/iss/iss_specifications.jl
models/SLICOT/mna1/mna1_run.jl
models/SLICOT/mna1/mna1_specifications.jl
models/SLICOT/mna5/mna5_run.jl
models/SLICOT/mna5/mna5_specifications.jl
models/SLICOT/motor/motor_run.jl
models/SLICOT/motor/motor_specifications.jl
models/SLICOT/pde/pde_run.jl
models/SLICOT/pde/pde_specifications.jl

This uncouples the specifications from `Reachability`.

Return dictionary from model specification
